version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mycalendar-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mycalendar-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mycalendar-api
    restart: unless-stopped
    ports:
      - "${APP_PORT}:3333"
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}"
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    networks:
      - mycalendar-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_data:

networks:
  mycalendar-network:
    driver: bridge
